# Generated by Django 4.2.24 on 2025-10-22 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskassignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_available', models.BooleanField(default=False)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskassignment.contributor')),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('contributor', 'date')},
            },
        ),
    ]
